### ISSUE TITLE
Mining, keyhunt or DoS is not allowed.

### ISSUE THREAD

**Issue by a1k-ghaz1** [adikul1023/webscan#1]
I was testing a website using this tool "https://github.com/adikul1023/webscan" but but my ip got blocked.
Here is message from my terminal window
//
Connecting to instance...
@@@@@ YOUR IP (**.**.**.**) HAS BEEN BANNED. Contact us if you feel that this is wrong. @@@@@
# NAME adm lg-ZDczZmYxMm **.**.**.**
Mining, keyhunt or DoS is not allowed.
🌈 We may have banned you by mistake. Please contact
a SysCop and let's talk about our feelings ❤️
Or get a TOKEN to prevent banning:
https://www.thc.org/segfault/token/)
Terminal Disconnected!
//

Please help and exclude the DDoS Code from this TOOL to avoid get BANNED mistakenly.

Thanks

**Comment by adikul1023** [comment]
This tool was adapted from rapidscan for college project work if you are facing any problems with this tool please contact the owner at https://github.com/skavngr/rapidscan
Thanks.
